CREATE DATABASE IF NOT EXISTS APP_MAIN;
CREATE DATABASE IF NOT EXISTS APP_AUDIT;

USE APP_MAIN;

CREATE TABLE IF NOT EXISTS customer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS address (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT,
  address VARCHAR(255) NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer(id)
);

USE APP_AUDIT;

CREATE TABLE IF NOT EXISTS audit_trail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value VARCHAR(255) NOT NULL
);
