version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'APP_MAIN'
      MYSQL_USER: 'cdcuser'
      MYSQL_PASSWORD: 'cdcpassword'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    networks:
      - cdc-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.8.1
    ports:
      - "8091:8080"
    networks:
      - cdc-network
    depends_on:
      - mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cdc-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - cdc-network
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8084:8081"
    networks:
      - cdc-network
    depends_on:
      - kafka

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.3.0
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/kafka/connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    ports:
      - "8083:8083"
    networks:
      - cdc-network
    depends_on:
      - kafka
      - schema-registry
      - mysql
    volumes:
      - ./debezium-connector:/kafka/connect

  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8084
    networks:
      - cdc-network
    depends_on:
      - kafka

  customer-service:
    image: customer:local
    ports:
      - "8100:8100"
    networks:
      - cdc-network
    depends_on:
      - kafka-connect

  audit-enrichment:
    image: audit-enrichment:local
    ports:
      - "8101:8080"
    networks:
      - cdc-network
    depends_on:
      - customer-service

  audit-ingestion:
    image: audit-ingestion:local
    ports:
      - "8102:8080"
    networks:
      - cdc-network
    depends_on:
        - audit-enrichment

  audit-query:
    image: audit-query:local
    ports:
      - "8103:8103"
    networks:
      - cdc-network
    depends_on:
      - audit-ingestion

networks:
  cdc-network:
    driver: bridge

volumes:
  mysql-data: