/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package app_main.APP_MAIN.customer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5070183138743869743L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"app_main.APP_MAIN.customer\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phone\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_date\",\"type\":{\"type\":\"string\",\"connect.version\":1,\"connect.default\":\"1970-01-01T00:00:00Z\",\"connect.name\":\"io.debezium.time.ZonedTimestamp\"},\"default\":\"1970-01-01T00:00:00Z\"},{\"name\":\"modified_date\",\"type\":{\"type\":\"string\",\"connect.version\":1,\"connect.default\":\"1970-01-01T00:00:00Z\",\"connect.name\":\"io.debezium.time.ZonedTimestamp\"},\"default\":\"1970-01-01T00:00:00Z\"},{\"name\":\"modified_by\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"record_status\",\"type\":{\"type\":\"string\",\"connect.default\":\"Active\"},\"default\":\"Active\"},{\"name\":\"correlation_id\",\"type\":[\"null\",\"string\"],\"default\":null}],\"connect.name\":\"app_main.APP_MAIN.customer.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Value> ENCODER =
      new BinaryMessageEncoder<Value>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Value> DECODER =
      new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Value> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Value> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Value> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Value to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Value from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Value instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Value fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.CharSequence name;
   private java.lang.CharSequence email;
   private java.lang.CharSequence phone;
   private java.lang.CharSequence created_date;
   private java.lang.CharSequence modified_date;
   private java.lang.CharSequence modified_by;
   private java.lang.CharSequence record_status;
   private java.lang.CharSequence correlation_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Value() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param email The new value for email
   * @param phone The new value for phone
   * @param created_date The new value for created_date
   * @param modified_date The new value for modified_date
   * @param modified_by The new value for modified_by
   * @param record_status The new value for record_status
   * @param correlation_id The new value for correlation_id
   */
  public Value(java.lang.Long id, java.lang.CharSequence name, java.lang.CharSequence email, java.lang.CharSequence phone, java.lang.CharSequence created_date, java.lang.CharSequence modified_date, java.lang.CharSequence modified_by, java.lang.CharSequence record_status, java.lang.CharSequence correlation_id) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.phone = phone;
    this.created_date = created_date;
    this.modified_date = modified_date;
    this.modified_by = modified_by;
    this.record_status = record_status;
    this.correlation_id = correlation_id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return email;
    case 3: return phone;
    case 4: return created_date;
    case 5: return modified_date;
    case 6: return modified_by;
    case 7: return record_status;
    case 8: return correlation_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: email = (java.lang.CharSequence)value$; break;
    case 3: phone = (java.lang.CharSequence)value$; break;
    case 4: created_date = (java.lang.CharSequence)value$; break;
    case 5: modified_date = (java.lang.CharSequence)value$; break;
    case 6: modified_by = (java.lang.CharSequence)value$; break;
    case 7: record_status = (java.lang.CharSequence)value$; break;
    case 8: correlation_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'created_date' field.
   * @return The value of the 'created_date' field.
   */
  public java.lang.CharSequence getCreatedDate() {
    return created_date;
  }


  /**
   * Sets the value of the 'created_date' field.
   * @param value the value to set.
   */
  public void setCreatedDate(java.lang.CharSequence value) {
    this.created_date = value;
  }

  /**
   * Gets the value of the 'modified_date' field.
   * @return The value of the 'modified_date' field.
   */
  public java.lang.CharSequence getModifiedDate() {
    return modified_date;
  }


  /**
   * Sets the value of the 'modified_date' field.
   * @param value the value to set.
   */
  public void setModifiedDate(java.lang.CharSequence value) {
    this.modified_date = value;
  }

  /**
   * Gets the value of the 'modified_by' field.
   * @return The value of the 'modified_by' field.
   */
  public java.lang.CharSequence getModifiedBy() {
    return modified_by;
  }


  /**
   * Sets the value of the 'modified_by' field.
   * @param value the value to set.
   */
  public void setModifiedBy(java.lang.CharSequence value) {
    this.modified_by = value;
  }

  /**
   * Gets the value of the 'record_status' field.
   * @return The value of the 'record_status' field.
   */
  public java.lang.CharSequence getRecordStatus() {
    return record_status;
  }


  /**
   * Sets the value of the 'record_status' field.
   * @param value the value to set.
   */
  public void setRecordStatus(java.lang.CharSequence value) {
    this.record_status = value;
  }

  /**
   * Gets the value of the 'correlation_id' field.
   * @return The value of the 'correlation_id' field.
   */
  public java.lang.CharSequence getCorrelationId() {
    return correlation_id;
  }


  /**
   * Sets the value of the 'correlation_id' field.
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.CharSequence value) {
    this.correlation_id = value;
  }

  /**
   * Creates a new Value RecordBuilder.
   * @return A new Value RecordBuilder
   */
  public static app_main.APP_MAIN.customer.Value.Builder newBuilder() {
    return new app_main.APP_MAIN.customer.Value.Builder();
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Value RecordBuilder
   */
  public static app_main.APP_MAIN.customer.Value.Builder newBuilder(app_main.APP_MAIN.customer.Value.Builder other) {
    if (other == null) {
      return new app_main.APP_MAIN.customer.Value.Builder();
    } else {
      return new app_main.APP_MAIN.customer.Value.Builder(other);
    }
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Value instance.
   * @param other The existing instance to copy.
   * @return A new Value RecordBuilder
   */
  public static app_main.APP_MAIN.customer.Value.Builder newBuilder(app_main.APP_MAIN.customer.Value other) {
    if (other == null) {
      return new app_main.APP_MAIN.customer.Value.Builder();
    } else {
      return new app_main.APP_MAIN.customer.Value.Builder(other);
    }
  }

  /**
   * RecordBuilder for Value instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Value>
    implements org.apache.avro.data.RecordBuilder<Value> {

    private long id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence email;
    private java.lang.CharSequence phone;
    private java.lang.CharSequence created_date;
    private java.lang.CharSequence modified_date;
    private java.lang.CharSequence modified_by;
    private java.lang.CharSequence record_status;
    private java.lang.CharSequence correlation_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(app_main.APP_MAIN.customer.Value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.created_date)) {
        this.created_date = data().deepCopy(fields()[4].schema(), other.created_date);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.modified_date)) {
        this.modified_date = data().deepCopy(fields()[5].schema(), other.modified_date);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.modified_by)) {
        this.modified_by = data().deepCopy(fields()[6].schema(), other.modified_by);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.record_status)) {
        this.record_status = data().deepCopy(fields()[7].schema(), other.record_status);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.correlation_id)) {
        this.correlation_id = data().deepCopy(fields()[8].schema(), other.correlation_id);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing Value instance
     * @param other The existing instance to copy.
     */
    private Builder(app_main.APP_MAIN.customer.Value other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.created_date)) {
        this.created_date = data().deepCopy(fields()[4].schema(), other.created_date);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.modified_date)) {
        this.modified_date = data().deepCopy(fields()[5].schema(), other.modified_date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.modified_by)) {
        this.modified_by = data().deepCopy(fields()[6].schema(), other.modified_by);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.record_status)) {
        this.record_status = data().deepCopy(fields()[7].schema(), other.record_status);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.correlation_id)) {
        this.correlation_id = data().deepCopy(fields()[8].schema(), other.correlation_id);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.email = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearEmail() {
      email = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.phone = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedDate() {
      return created_date;
    }


    /**
      * Sets the value of the 'created_date' field.
      * @param value The value of 'created_date'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setCreatedDate(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.created_date = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'created_date' field has been set.
      * @return True if the 'created_date' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'created_date' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearCreatedDate() {
      created_date = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'modified_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getModifiedDate() {
      return modified_date;
    }


    /**
      * Sets the value of the 'modified_date' field.
      * @param value The value of 'modified_date'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setModifiedDate(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.modified_date = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'modified_date' field has been set.
      * @return True if the 'modified_date' field has been set, false otherwise.
      */
    public boolean hasModifiedDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'modified_date' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearModifiedDate() {
      modified_date = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'modified_by' field.
      * @return The value.
      */
    public java.lang.CharSequence getModifiedBy() {
      return modified_by;
    }


    /**
      * Sets the value of the 'modified_by' field.
      * @param value The value of 'modified_by'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setModifiedBy(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.modified_by = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'modified_by' field has been set.
      * @return True if the 'modified_by' field has been set, false otherwise.
      */
    public boolean hasModifiedBy() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'modified_by' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearModifiedBy() {
      modified_by = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'record_status' field.
      * @return The value.
      */
    public java.lang.CharSequence getRecordStatus() {
      return record_status;
    }


    /**
      * Sets the value of the 'record_status' field.
      * @param value The value of 'record_status'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setRecordStatus(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.record_status = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'record_status' field has been set.
      * @return True if the 'record_status' field has been set, false otherwise.
      */
    public boolean hasRecordStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'record_status' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearRecordStatus() {
      record_status = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlation_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCorrelationId() {
      return correlation_id;
    }


    /**
      * Sets the value of the 'correlation_id' field.
      * @param value The value of 'correlation_id'.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder setCorrelationId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.correlation_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'correlation_id' field has been set.
      * @return True if the 'correlation_id' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'correlation_id' field.
      * @return This builder.
      */
    public app_main.APP_MAIN.customer.Value.Builder clearCorrelationId() {
      correlation_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Value build() {
      try {
        Value record = new Value();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.email = fieldSetFlags()[2] ? this.email : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.phone = fieldSetFlags()[3] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.created_date = fieldSetFlags()[4] ? this.created_date : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.modified_date = fieldSetFlags()[5] ? this.modified_date : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.modified_by = fieldSetFlags()[6] ? this.modified_by : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.record_status = fieldSetFlags()[7] ? this.record_status : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.correlation_id = fieldSetFlags()[8] ? this.correlation_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Value>
    WRITER$ = (org.apache.avro.io.DatumWriter<Value>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Value>
    READER$ = (org.apache.avro.io.DatumReader<Value>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeString(this.email);

    if (this.phone == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.phone);
    }

    out.writeString(this.created_date);

    out.writeString(this.modified_date);

    if (this.modified_by == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.modified_by);
    }

    out.writeString(this.record_status);

    if (this.correlation_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.correlation_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.phone = null;
      } else {
        this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
      }

      this.created_date = in.readString(this.created_date instanceof Utf8 ? (Utf8)this.created_date : null);

      this.modified_date = in.readString(this.modified_date instanceof Utf8 ? (Utf8)this.modified_date : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.modified_by = null;
      } else {
        this.modified_by = in.readString(this.modified_by instanceof Utf8 ? (Utf8)this.modified_by : null);
      }

      this.record_status = in.readString(this.record_status instanceof Utf8 ? (Utf8)this.record_status : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.correlation_id = null;
      } else {
        this.correlation_id = in.readString(this.correlation_id instanceof Utf8 ? (Utf8)this.correlation_id : null);
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.phone = null;
          } else {
            this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
          }
          break;

        case 4:
          this.created_date = in.readString(this.created_date instanceof Utf8 ? (Utf8)this.created_date : null);
          break;

        case 5:
          this.modified_date = in.readString(this.modified_date instanceof Utf8 ? (Utf8)this.modified_date : null);
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.modified_by = null;
          } else {
            this.modified_by = in.readString(this.modified_by instanceof Utf8 ? (Utf8)this.modified_by : null);
          }
          break;

        case 7:
          this.record_status = in.readString(this.record_status instanceof Utf8 ? (Utf8)this.record_status : null);
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.correlation_id = null;
          } else {
            this.correlation_id = in.readString(this.correlation_id instanceof Utf8 ? (Utf8)this.correlation_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










